### PR TITLE
Updated URL

### PR DESCRIPTION
**Pull request by mattannand**
Changed URL from "bbb.testpro.io" to "testpro.io"

### CODE REVIEW

**Comment by Berichicko** [comment]
Please finish the homework!You got this problem, please correct it. 

image

**Comment by mattannand** [comment]
What do you mean?

**Comment by mattannand** [comment]
> Please finish the homework!You got this problem, please correct it.
> 
> image

what do you mean?

**Comment by Berichicko** [comment]
> > Please finish the homework!You got this problem, please correct it.
> > image
> 
> what do you mean?

For example

Test status_en

Test error_en

**Pull request closed without merging**
