### PR TITLE
Homework15

### PR DESCRIPTION
**Pull request by JuliaBurkovaQA**

### CODE REVIEW

**Comment by Berichicko** [comment]
Please finish the homework! You got this problem, please correct it. 

Test error

image

HINT

How to analyze the results of tests.

Test status: 
	
Test error (red). This status is assigned to tests that caused an exception from the tested source code.


Test error_ru

**Comment by JuliaBurkovaQA** [comment]
I think I cloned the wrong repository. I tried to change, but I can't. Maybe I do something wrong. I can't to clone new one(( Please help me.
Screenshot 2023-04-22 153320

**Comment by Berichicko** [comment]
Hello

Please, re-submit homework for review

**Comment by JuliaBurkovaQA** [comment]
I figured it out and fixed it.

**Comment by Berichicko** [comment]
Hello 
Your homework 15 is checked
**You’re doing great! Keep it up! Very fine!** 
💖Best wishes, the team HW (Alex,  aliaksandr@testpro.io)!💖

giphy


image

**Comment by JuliaBurkovaQA** [comment]
> Hello Your homework 15 is checked **You’re doing great! Keep it up! Very fine!** 💖Best wishes, the team HW (Alex, [aliaksandr@testpro.io](mailto:aliaksandr@testpro.io))!💖
> 
> giphy [ giphy ](https://user-images.githubusercontent.com/104761482/224489514-d22b527b-705f-4444-ab44-b5d0fded7d97.gif) [ ](https://user-images.githubusercontent.com/104761482/224489514-d22b527b-705f-4444-ab44-b5d0fded7d97.gif)
> 
> image

**Pull request closed without merging**
