### PR TITLE
Homework17

### PR DESCRIPTION
**Pull request by JuliaBurkovaQA**
Hello! Alex, please help. I can't understand. I either have successful TestNG test or HomeWork17 test. Different song searches gives different results. I don’t know if I have a test or not. One of them always shows that the problem is the locator of the message banner (.success), but there are not so many options and I tried everything. I don't see where is mistake(

### CODE REVIEW

**Comment by Berichicko** [comment]
> I can't understand. I either have successful TestNG test or HomeWork17 test. Different song searches gives different results. I don’t know if I have a test or not. One of them always shows that the problem is the locator of the message banner (.success), but there are not so many options and I tried everything. I don't see where is mistake(

Hello! Thank you! I'll try to help you!

The message banner (.success) doesn't appear because the song is already added to the playlist.

**Solution:** you can create a test suite for creating a playlist, then adding a song and deleting the playlist.

It's good practice to clean up after your test data.

For example, create a test for creating a playlist, then create a test for adding a song to the playlist, and then create a test for verifying the deletion of the playlist.

**Comment by Berichicko** [comment]
Hello 
Your homework 17 is checked
**You’re doing great! Keep it up! Very fine!** 
💖Best wishes, the team HW (Alex,  aliaksandr@testpro.io)!💖

giphy


Screenshot_2

**Comment by JuliaBurkovaQA** [comment]
> Solution

**Comment by JuliaBurkovaQA** [comment]
Thanks! And what about adding a song to the playlist, seeing the banner and after deleting a song from the playlist?

**Pull request closed without merging**
